### ISSUE TITLE
鉴权没有使用

### ISSUE THREAD

**Issue by cs81** [kubesre/genbu#12]
大佬，routers.go里面的鉴权好像没有使用，鉴权有问题还是

**Comment by cf1998** [comment]
// 不需要做鉴权的接口 PublicGroup
	PublicGroup := r.Group("/api")
	{
		base.InitBaseRouters(PublicGroup, authMiddleware)
	}
	// 需要做鉴权的接口
	PrivateGroup := r.Group("/api")
	PrivateGroup.Use(authMiddleware.MiddlewareFunc())
	// 鉴权
	//PrivateGroup.Use(gin.Recovery()).
	//	Use(middles.OperationLog()).Use(middles.CasbinMiddle())
	{
		system.InitUserRouters(PrivateGroup, authMiddleware)
		system.InitRolesRouters(PrivateGroup)
		system.InitDeptRouters(PrivateGroup)
		system.InitMenusRouters(PrivateGroup)
		system.InitPolicyRouters(PrivateGroup)
		system.InitLogRouters(PrivateGroup)
		kubernetes.InitClusterRouters(PrivateGroup)
		kubernetes.InitNodeRouters(PrivateGroup)
	}
	r.NoRoute(func(ctx *gin.Context) {
		global.ReturnContext(ctx).Failed("fail", "该接口未开放")
		return
	})
	return r
}

已优化这块代码
