### ISSUE TITLE
casbin有问题

### ISSUE THREAD

**Issue by cs81** [kubesre/genbu#15]
// 鉴权
//PrivateGroup.Use(gin.Recovery()).
//	Use(middles.OperationLog()).Use(middles.CasbinMiddle())
我打开这个注释后，查询会报错
![image](https://github.com/kubesre/genbu/assets/52037441/4e971766-d19e-476e-8083-9293453b3635)

**Comment by zxl00** [comment]
使用最新的代码

**Comment by zxl00** [comment]
@cs81 可以使用genbu的代码，将kubernetes相关的删除掉即可，go-easy-admin还没有更新最新的代码

**Comment by cs81** [comment]
好的
